"""migration16

Revision ID: 0b215a08c270
Revises: a7ae3289d5fa
Create Date: 2021-02-19 15:12:30.229485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b215a08c270'
down_revision = 'a7ae3289d5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FixEmployee',
    sa.Column('fixid', sa.Integer(), nullable=True),
    sa.Column('employeeid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employeeid'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['fixid'], ['user.id'], )
    )
    op.drop_table('fix_employee')
    op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'employee', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_table('fix_employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fixid', sa.INTEGER(), nullable=True),
    sa.Column('employeeid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['employeeid'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['fixid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('FixEmployee')
    # ### end Alembic commands ###
