"""migration3

Revision ID: 4c19e0873126
Revises: 32b4727d7015
Create Date: 2021-02-02 14:42:52.380865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c19e0873126'
down_revision = '32b4727d7015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fix', sa.Column('completed', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_column('fix', 'completed')
    # ### end Alembic commands ###
