"""migration9

Revision ID: 72e6cb3c83c0
Revises: e56eb7b32e6a
Create Date: 2021-02-13 19:44:23.205149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e6cb3c83c0'
down_revision = 'e56eb7b32e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    op.add_column('fix', sa.Column('iduser', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    op.add_column('fix_detail', sa.Column('iduser', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    op.drop_column('fix_detail', 'iduser')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_column('fix', 'iduser')
    # op.drop_constraint(None, 'client', type_='foreignkey')
    # ### end Alembic commands ###
