"""migration12

Revision ID: 78cfe04e9320
Revises: b82c30a54e8f
Create Date: 2021-02-18 14:01:34.218453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cfe04e9320'
down_revision = 'b82c30a54e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    op.add_column('fix', sa.Column('image_path', sa.String(), nullable=True))
    # op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    # op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_column('fix', 'image_path')
    # op.drop_constraint(None, 'client', type_='foreignkey')
    # ### end Alembic commands ###
