"""migration15

Revision ID: 7bba1f7e75c9
Revises: b9b76ad9afd3
Create Date: 2021-02-19 13:53:12.090342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bba1f7e75c9'
down_revision = 'b9b76ad9afd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fix_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixid', sa.Integer(), nullable=True),
    sa.Column('employeeid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employeeid'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['fixid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'employee', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_table('fix_employee')
    # ### end Alembic commands ###
