"""migration25

Revision ID: 7d182309d762
Revises: e21670cb5cd9
Create Date: 2021-02-23 20:05:58.073411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d182309d762'
down_revision = 'e21670cb5cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'employee', 'user', ['iduser'], ['id'])
    op.add_column('fix', sa.Column('idpriority', sa.Integer(), nullable=True))
    # op.alter_column('fix', 'loadDate',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    op.create_foreign_key(None, 'fix', 'priority', ['idpriority'], ['id'])
    # op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.alter_column('fix', 'loadDate',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    op.drop_column('fix', 'idpriority')
    # op.drop_constraint(None, 'employee', type_='foreignkey')
    # op.drop_constraint(None, 'client', type_='foreignkey')
    # ### end Alembic commands ###
