"""migration20

Revision ID: 8a1024f51ef0
Revises: 67361fc41b56
Create Date: 2021-02-19 15:44:02.967453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1024f51ef0'
down_revision = '67361fc41b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FixEmployee',
    sa.Column('fixid', sa.Integer(), nullable=True),
    sa.Column('employeeid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employeeid'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['fixid'], ['fix.id'], )
    )
    op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'employee', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_table('FixEmployee')
    # ### end Alembic commands ###
