"""migration23

Revision ID: 8eec5c3a905e
Revises: dc222d70260c
Create Date: 2021-02-23 14:44:05.549896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eec5c3a905e'
down_revision = 'dc222d70260c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'employee', 'user', ['iduser'], ['id'])
    op.add_column('fix', sa.Column('loadDate', sa.DateTime()))
    # op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    # op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_column('fix', 'loadDate')
    # op.drop_constraint(None, 'employee', type_='foreignkey')
    # op.drop_constraint(None, 'client', type_='foreignkey')
    # ### end Alembic commands ###
