"""migration14

Revision ID: b9b76ad9afd3
Revises: 98d42baef9b0
Create Date: 2021-02-19 12:03:33.421490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b76ad9afd3'
down_revision = '98d42baef9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('iduser', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'employee', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    # op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'iduser')
    # op.drop_constraint(None, 'client', type_='foreignkey')
    # ### end Alembic commands ###
