"""migration18

Revision ID: c819615a1628
Revises: 1d5753a7945b
Create Date: 2021-02-19 15:36:34.248414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c819615a1628'
down_revision = '1d5753a7945b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'FixEmployee', type_='foreignkey')
    op.create_foreign_key(None, 'FixEmployee', 'fix', ['fixid'], ['id'])
    op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'employee', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    # op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'employee', type_='foreignkey')
    # op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'FixEmployee', type_='foreignkey')
    op.drop_constraint(None, 'FixEmployee', 'user', ['fixid'], ['id'])
    # ### end Alembic commands ###
