"""migration21

Revision ID: eb178a04c4af
Revises: 8a1024f51ef0
Create Date: 2021-02-20 15:12:22.771812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb178a04c4af'
down_revision = '8a1024f51ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'client', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'employee', 'user', ['iduser'], ['id'])
    op.add_column('fix', sa.Column('awb', sa.String(), nullable=True))
    # op.create_foreign_key(None, 'fix', 'user', ['iduser'], ['id'])
    # op.create_foreign_key(None, 'fix', 'fix_detail', ['idfixType'], ['id'])
    # op.create_foreign_key(None, 'fix_detail', 'user', ['iduser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'fix_detail', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    # op.drop_constraint(None, 'fix', type_='foreignkey')
    op.drop_column('fix', 'awb')
    # op.drop_constraint(None, 'employee', type_='foreignkey')
    # op.drop_constraint(None, 'client', type_='foreignkey')
    # ### end Alembic commands ###
