"""Initial migration.

Revision ID: 75999ae8659b
Revises: 
Create Date: 2021-02-01 19:59:23.428432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75999ae8659b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fix', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fix', 'description')
    # ### end Alembic commands ###
